// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_middleware from "./routes/api/_middleware.ts";
import * as $api_links from "./routes/api/links.ts";
import * as $api_ping from "./routes/api/ping.ts";
import * as $portal from "./routes/portal.tsx";
import * as $PortalIsland from "./islands/PortalIsland.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/_middleware.ts": $api_middleware,
    "./routes/api/links.ts": $api_links,
    "./routes/api/ping.ts": $api_ping,
    "./routes/portal.tsx": $portal,
  },
  islands: {
    "./islands/PortalIsland.tsx": $PortalIsland,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
