name: Deploy
on:
  push:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Fake env
        run: |
          cat <<EOF > .env
          OAUTH2_AUTHORIZE_URL=none
          OAUTH2_TOKEN_URL=none
          OAUTH2_CLIENT_ID=none
          OAUTH2_CLIENT_SECRET=none
          EOF

      - name: Build step
        run: "deno task build"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "jmsn-link"
          entrypoint: "main.ts"
          root: "."
          
          
